### ISSUE TITLE
unable to start 

### ISSUE THREAD

**Issue by to1source** [Coolpy7/Coolpy7#1]
warning: test upstream error: dial tcp 127.0.0.1:1883: connect: connection refused

**Comment by jacoblai** [comment]
如果是ws poxy 出现的话，应该是因为连接不到cp7，确认下co7运行在什么ip或是否正常启动，然后通过设置ws poxy启动参数来改变cp7地址，默认是127.0.0.1:1883是在cp 7和ws poxy 在同一机器的情况下，如果不在同一台机器就把127.0.0.1改为cp 7当前真实地址即可。

**Comment by joel-chu** [comment]
是在同机运行。那是否要先启动coolpy7然后再启动ws呢?

**Comment by jacoblai** [comment]
是的，先启动cp7即可，此功能只是一个启动时验证能不能正常与cp7核心服务连接成功，如果你只是因为启动顺序的出现这个提示可以忽略它，只要你确保相关依赖服务和网络配置没有问题系统服务还是一样会正常提供的。
