### ISSUE TITLE
客户端定期掉线

### ISSUE THREAD

**Issue by soitun** [Coolpy7/Coolpy7#10]
内核按默认启动
客户端： github.com/eclipse/paho.mqtt.golang 
1，客户端连接后会订阅指定主题  update/status
2，客户端每隔15秒上报一次数据
发现客户端会定期掉线，请问内核启动时需要配置什么参数，谢谢

**Comment by jacoblai** [comment]
首先考虑是否客户端库有问题，内核默认参数是不会这样的，你可以换个客户端库测试一下。



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: soitun <notifications@github.com&gt;
发送时间: 2020年11月26日 09:09
收件人: Coolpy7/Coolpy7 <Coolpy7@noreply.github.com&gt;
抄送: Subscribed <subscribed@noreply.github.com&gt;
主题: 回复：[Coolpy7/Coolpy7] 客户端定期掉线 (#10)





 
内核按默认启动
 客户端： github.com/eclipse/paho.mqtt.golang
 1，客户端连接后会订阅指定主题  update/status
 2，客户端每隔15秒上报一次数据
 发现客户端会定期掉线，请问内核启动时需要配置什么参数，谢谢

**Comment by soitun** [comment]
好的，我先换下试试，谢谢
