### ISSUE TITLE
如何检测客户端掉线

### ISSUE THREAD

**Issue by soitun** [Coolpy7/Coolpy7#11]
我现在是通过扩展服务器的 /term 事件来做客户端掉线检测，然后更新数据库的客户端在线状态
在客户端设置了keeplive ， 发现不管设置keeplive 为多少，客户端还是会经常离线。
请问有什么更好的方案来检测，谢谢

**Comment by jacoblai** [comment]
请问你的应用技术是哪方面的？单片机？app？网页？



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: soitun <notifications@github.com&gt;
发送时间: 2020年11月30日 16:35
收件人: Coolpy7/Coolpy7 <Coolpy7@noreply.github.com&gt;
抄送: Subscribed <subscribed@noreply.github.com&gt;
主题: 回复：[Coolpy7/Coolpy7] 如何检测客户端掉线 (#11)





 
我现在是通过扩展服务器的 /term 事件来做客户端掉线检测，然后更新数据库的客户端在线状态
 在客户端设置了keeplive ， 发现不管设置keeplive 为多少，客户端还是会经常离线。
 请问有什么更好的方案来检测，谢谢

**Comment by jacoblai** [comment]
请把你在使用的客户端库告诉我，我去复现一下。

**Comment by soitun** [comment]
我用的是
github.com/eclipse/paho.mqtt.golang
谢谢

**Comment by jacoblai** [comment]
好的，没有特殊环境是吗？直接amd64运行？



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: soitun <notifications@github.com&gt;
发送时间: 2020年12月2日 09:25
收件人: Coolpy7/Coolpy7 <Coolpy7@noreply.github.com&gt;
抄送: Li Donghai <5241871@qq.com&gt;, Comment <comment@noreply.github.com&gt;
主题: 回复：[Coolpy7/Coolpy7] 如何检测客户端掉线 (#11)





 
我用的是
 github.com/eclipse/paho.mqtt.golang
 谢谢

**Comment by soitun** [comment]
是的，没有特殊的环境的

**Comment by jacoblai** [comment]
OK



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: soitun <notifications@github.com&gt;
发送时间: 2020年12月2日 09:28
收件人: Coolpy7/Coolpy7 <Coolpy7@noreply.github.com&gt;
抄送: Li Donghai <5241871@qq.com&gt;, Comment <comment@noreply.github.com&gt;
主题: 回复：[Coolpy7/Coolpy7] 如何检测客户端掉线 (#11)





 
是的，没有特殊的环境的

**Comment by jacoblai** [comment]
请参考这个订阅示例：https://github.com/Coolpy7/coolpy7_benchmark/blob/master/clients_samples/paho_golang_sub_client.go
这里有两点需要说明：1.SetDefaultPublishHandler里的处理代码必须没有阻塞，需要现在这样的代码去处理接收处理逻辑。2.如果网络环境极为不稳定，可以把我注释掉的自动重连功能开启，再把clear session设置为false.

**Comment by soitun** [comment]
谢谢，马上试下

**Comment by soitun** [comment]
按上面的例子已经理好，谢谢

**Comment by jacoblai** [comment]
好的，请关闭本提问。



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: soitun <notifications@github.com&gt;
发送时间: 2020年12月4日 09:06
收件人: Coolpy7/Coolpy7 <Coolpy7@noreply.github.com&gt;
抄送: Li Donghai <5241871@qq.com&gt;, Comment <comment@noreply.github.com&gt;
主题: 回复：[Coolpy7/Coolpy7] 如何检测客户端掉线 (#11)





 
按上面的例子已经理好，谢谢

**Comment by jacoblai** [comment]
还有一个问题需要注意，不然的话很可能会把系统的cpu用尽，原因是for goruntine时没有没有做时间中断，所以cpu会一直占用很高，解决办法是增加for的time.sleep，代码如下：
```
for {
		select {
		case incoming := <-d.Choke:
			//d.mqttHandler(incoming.Client, incoming.Message)
		case <-d.Quit:
			return
		default:
			time.Sleep(20*time.Millisecond) //必须增加此句代码让for行业适当的中断时间，cpu才能合理释放。
		}
	}
```
