### ISSUE TITLE
websocket 连接慢 

### ISSUE THREAD

**Issue by soitun** [Coolpy7/Coolpy7#12]
用mqtt.js 连接websocket 代理很慢

**Comment by jacoblai** [comment]
请转用paho的mqttjs包，参考coopy7组织下的聊天室示例代码。



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: soitun <notifications@github.com&gt;
发送时间: 2020年12月4日 09:12
收件人: Coolpy7/Coolpy7 <Coolpy7@noreply.github.com&gt;
抄送: Subscribed <subscribed@noreply.github.com&gt;
主题: 回复：[Coolpy7/Coolpy7] websocket 连接慢  (#12)





 
用mqtt.js 连接websocket 代理很慢

**Comment by soitun** [comment]
我改下试试， 有结果后这里反馈，谢谢

**Comment by soitun** [comment]
更换为paho的mqttjs包后，问题完美解决，谢谢

**Comment by jacoblai** [comment]
好的



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: soitun <notifications@github.com&gt;
发送时间: 2020年12月8日 11:08
收件人: Coolpy7/Coolpy7 <Coolpy7@noreply.github.com&gt;
抄送: Li Donghai <5241871@qq.com&gt;, Comment <comment@noreply.github.com&gt;
主题: 回复：[Coolpy7/Coolpy7] websocket 连接慢  (#12)

**Comment by jacoblai** [comment]
最新添加了mqttjs的coolpy7示例：https://github.com/Coolpy7/mqttjs_browser_client_demo
