### ISSUE TITLE
测试的时候go_build_Coolpy7_ws_go_linux,出现runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by 1421855993** [Coolpy7/Coolpy7#13]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x50 pc=0x55a675]

goroutine 18 [running]:
bridge.(*WsBridge).Receive(0xc0064d42c0, 0xc000066f88, 0x400)
        /Users/jac/GolandProjects/new/coolpy7/src/bridge/wsbridge.go:96 +0xb5
main.main.func1.2(0xb5655d4cae970001)
        /Users/jac/GolandProjects/new/coolpy7/Coolpy7_ws.go:77 +0x66
netpoll.poller.Start.func1(0x1)
        /Users/jac/GolandProjects/new/coolpy7/src/netpoll/netpoll_epoll.go:46 +0x8f
netpoll.(*Epoll).wait(0xc0000c0380, 0x5c1d28)
        /Users/jac/GolandProjects/new/coolpy7/src/netpoll/epoll.go:246 +0x37e
created by netpoll.EpollCreate
        /Users/jac/GolandProjects/new/coolpy7/src/netpoll/epoll.go:106 +0x1d7

**Comment by jacoblai** [comment]
已经发布了新的版本，请下载再测试一下。
