### ISSUE TITLE
启动主程序，提示找不到ip地址，求解决方法

### ISSUE THREAD

**Issue by sxcisco** [Coolpy7/Coolpy7#14]
`[root@fair-beams-4 mqtt]# ./go_build_Coolpy7_go_linux
2021/04/06 14:42:43 Coolpy7 cluster Failed to get final advertise address: No private IP address found, and explicit IP not provided
`
加上-l 64.64.247.10:1883还是提示上面的错误，
下面是ifconfig信息
`[root@fair-beams-4 mqtt]# ifconfig
eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 64.64.247.10  netmask 255.255.255.0  broadcast 64.64.247.255
        inet6 fe80::a8aa:ff:fe16:aa68  prefixlen 64  scopeid 0x20<link>
        ether aa:aa:00:16:aa:68  txqueuelen 1000  (Ethernet)
        RX packets 10824481  bytes 19227927461 (17.9 GiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 9332837  bytes 19443347210 (18.1 GiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

eth1: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        ether ba:aa:00:16:aa:68  txqueuelen 1000  (Ethernet)
        RX packets 2305736  bytes 784729966 (748.3 MiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 39294  bytes 5727368 (5.4 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        inet6 ::1  prefixlen 128  scopeid 0x10<host>
        loop  txqueuelen 1000  (Local Loopback)
        RX packets 8256734  bytes 19270103438 (17.9 GiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 8256734  bytes 19270103438 (17.9 GiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
`
求解决方案；

**Comment by jacoblai** [comment]
禁用操作系统的IPV6功能。



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: sxcisco ***@***.***&gt;
发送时间: 2021年4月6日 15:24
收件人: Coolpy7/Coolpy7 ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: 回复：[Coolpy7/Coolpy7] 启动主程序，提示找不到ip地址，求解决方法 (#14)

**Comment by jacoblai** [comment]
请下载最新版本v7.3.3.9使用即可。
