### ISSUE TITLE
qos为1或者2的消息没有被持久化保存

### ISSUE THREAD

**Issue by StrangeYear** [Coolpy7/Coolpy7#2]
状况：客户端1订阅qos1的主题之后离线，客户端2发送qos1的消息到这个主题。重启coolpy7服务。客户端1重新上线，没有收到持久化消息。不过订阅关系倒是保存下来了。

**Comment by jacoblai** [comment]
检查一下你的连接客户端是不是连接参数里的clearsession参数为true，如果是的话改为false应该就可以正常了

**Comment by StrangeYear** [comment]
clean是false的。具体你可以按照我说的测试一下。

**Comment by StrangeYear** [comment]
在coolpy7服务器不重启的情况下是正常的。我估计是服务启动的时候没有把缓存里的消息加载进来还是怎么的？

**Comment by jacoblai** [comment]
我这边测试是没有问题的，你可以要换一些测试方式去确认一下问题，我这边的测试顺序是：
1.客户端连接并以qos1订阅主题，
2.另一个客户端发送pub消息到对应主题qos1，
3.关闭第一步客户端，
4.再用第二步客户端继续pub消息，
5.重新启动第一步客户端
注意：接收消息的客户端clear session设置为false

**Comment by StrangeYear** [comment]
我的测试步骤是这样的：cleansession是false
1.客户端连接并以qos1订阅主题，
2.另一个客户端发送pub消息到对应主题qos1，
3.关闭第一步客户端，
4.再用第二步客户端继续pub消息，
5.重启coolpy服务
6.重新启动第一步客户端
所以我的疑问是 在coolpy服务重启的时候 没有把消息持久化吗

**Comment by jacoblai** [comment]
此bug已修复，请下载最新版本测试
