### ISSUE TITLE
Coolpy7 kernel extension issue

### ISSUE THREAD

**Issue by weiliudong** [Coolpy7/Coolpy7#3]
![UNADJUSTEDNONRAW_thumb_1](https://user-images.githubusercontent.com/24930918/58691043-85e5d380-83bd-11e9-9759-267bf0ee5f9a.jpg)

plugin: not implemented

Linux li818-156 3.16.0-6-amd64 #1 SMP Debian 3.16.56-1+deb8u1 (2018-05-08) x86_64 GNU/Linux

go version go1.12.5 linux/amd64

go env

GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/root/work"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build291973316=/tmp/go-build -gno-record-gcc-switches"

This is the problem I encountered when I expanded the Coolpy7 kernel function hot load plugin. May I have any problems with this? Always encountered plugin: not implemented

**Comment by jacoblai** [comment]
很可能插件编译环境与运行环境不一致造成，
1.启动cp7 后看cp7 的编译go版本
2.在运行环境安装一样版本号的go环境
3.在运行环境重新编译插件

**Comment by weiliudong** [comment]
@jacoblai The method you said, I tried it, it still didn't work.
This is the go environment on my server.
![image](https://user-images.githubusercontent.com/24930918/58692879-250cca00-83c2-11e9-981a-dbb9012f8ab4.png)

go version go1.12.5 linux/amd64
2019/05/31 08:35:25 Coolpy7 v7.2.0.8 tcp [::]:1883 plugin build golang v1.12.5
But still appears plugin: not implemented
This makes me very depressed.

**Comment by jacoblai** [comment]
你确定你是在本项目中的make.sh来生成插件的吗？

**Comment by zhouBq1** [comment]
同样的问题，请问解决了吗？

**Comment by zhouBq1** [comment]
@weiliudong @jacoblai 请问解决了吗，遇到了同样的问题

**Comment by jacoblai** [comment]
初步判断是没有按指定的模板来编写插件，请参阅手册：https://coolpy7.gitbook.io/coolpy7book/kai-shi-shi-yong/nei-he-gong-neng-kuo-zhan， 一定要参考此项源代码中的make.sh来分析编译过程。

**Comment by zhouBq1** [comment]
编译环境是这样的
<img width="824" alt="屏幕快照 2019-06-18 上午10 18 27" src="https://user-images.githubusercontent.com/15841920/59648700-90241200-91b2-11e9-9d0c-4ca5eafe186f.png">

<img width="644" alt="屏幕快照 2019-06-18 上午10 20 27" src="https://user-images.githubusercontent.com/15841920/59648758-c497ce00-91b2-11e9-838d-4c42249349df.png">

**Comment by zhouBq1** [comment]
@jacoblai 这样环境还有什么问题吗？

**Comment by jacoblai** [comment]
看当前系统里安装的go是什么版本，看下和 coolpy7的 1.12.5是不是一至

**Comment by zhouBq1** [comment]
@jacoblai 上面图上的go1.12.5是编译的go版本

**Comment by jacoblai** [comment]
把go env发现来看下

**Comment by zhouBq1** [comment]
<img width="819" alt="屏幕快照 2019-06-18 上午11 06 54" src="https://user-images.githubusercontent.com/15841920/59650648-5276b780-91b9-11e9-9b78-678662aeb5b7.png">

**Comment by jacoblai** [comment]
开个ssh给我进去看下

**Comment by zhouBq1** [comment]
是本机测试的，core是用的docker开的，编译是在linux上

**Comment by jacoblai** [comment]
建议先不要用 docker直接在本机测试插件编译，成功后可以进入docker里边再次编译，然后把当前环境作为插件打包环境为的产环境提供打包服务
