### ISSUE TITLE
组播功能无效

### ISSUE THREAD

**Issue by apm70plus** [Coolpy7/Coolpy7#6]
版本v7.2.0.8，采用chrom插件MQTTLens 测试，普通的topic能够正常发布和订阅消息，但是组播消息
$share/group1  和 $queue/group1 发布、订阅无法收到消息。是什么原因呢？
而且，发布组播消息到topic后，再次发布普通消息也没有任何响应了，就像服务卡在哪里了

**Comment by jacoblai** [comment]
有没有使用插件功能？是很单纯的直接启动一个cp7服务端做测试对吗？

**Comment by apm70plus** [comment]
没有启用插件，单纯的cp7服务

**Comment by jacoblai** [comment]
请到release下载修正此问题后的版本：https://github.com/Coolpy7/Coolpy7/releases

**Comment by apm70plus** [comment]
$share 模式已经好用了，$queue模式仍然不通。我可以先用着$share模式

**Comment by jacoblai** [comment]
我这边$queue测试是正常通过的。你可以考滤先清一个data文件夹下的所有数据文件，重启cp7再测试。

**Comment by apm70plus** [comment]
使用中发现如下异常：
```
panic: sync: negative WaitGroup counter

goroutine 7695 [running]:
sync.(*WaitGroup).Add(0xc00406d150, 0xffffffffffffffff)
	/usr/local/go/src/sync/waitgroup.go:74 +0x139
sync.(*WaitGroup).Done(...)
	/usr/local/go/src/sync/waitgroup.go:99
broker.(*Engine).TopicQueueRunner.func1(0xc0047ec000, 0xc006e7a640, 0xc00406d150)
	/Users/jac/GolandProjects/new/coolpy7/src/broker/engine.go:280 +0x349
created by broker.(*Engine).TopicQueueRunner
	/Users/jac/GolandProjects/new/coolpy7/src/broker/engine.go:247 +0x297
```
问题原因已经找到：
如果没有订阅者，或者订阅者取消了订阅，发布消息到特定的topic，就会报上面的异常，导致服务down掉。有订阅者的情况下一切正常

**Comment by jacoblai** [comment]
感谢你提供的问题，此bug已修复，请到release下载 7.2.1.0 版本即可。
