### ISSUE TITLE
是个好项目！

### ISSUE THREAD

**Issue by itMuYou** [Coolpy7/Coolpy7#7]
是个很好的项目，但是星星怎么这么少啊！请问有qq群之类的吗？不然都不好交流，不好推广啊

**Comment by jacoblai** [comment]
官网上有qq群信息，Coolpy.net



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: itMuYou <notifications@github.com&gt;
发送时间: 2020年8月12日 21:20
收件人: Coolpy7/Coolpy7 <Coolpy7@noreply.github.com&gt;
抄送: Subscribed <subscribed@noreply.github.com&gt;
主题: 回复：[Coolpy7/Coolpy7] 是个好项目！ (#7)





 
是个很好的项目，但是星星怎么这么少啊！请问有qq群之类的吗？不然都不好交流，不好推广啊
