### ISSUE TITLE
如何启用帐号密码认证

### ISSUE THREAD

**Issue by soitun** [Coolpy7/Coolpy7#9]
如何启用帐号密码认证，确保只有认证通过的客户端才能发布和订阅消息，谢谢

**Comment by jacoblai** [comment]
请使用扩散服务，开源的，相关说明在官网技术文档中。



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: soitun <notifications@github.com&gt;
发送时间: 2020年10月27日 10:25
收件人: Coolpy7/Coolpy7 <Coolpy7@noreply.github.com&gt;
抄送: Subscribed <subscribed@noreply.github.com&gt;
主题: 回复：[Coolpy7/Coolpy7] 如何启用帐号密码认证 (#9)





 
如何启用帐号密码认证，确保只有认证通过的客户端才能发布和订阅消息，谢谢

**Comment by soitun** [comment]
看到了，谢谢
